[2023-01-21T03:08:07.926+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_spark_operator.python_job manual__2023-01-21T01:12:16.362883+00:00 [queued]>
[2023-01-21T03:08:07.933+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_spark_operator.python_job manual__2023-01-21T01:12:16.362883+00:00 [queued]>
[2023-01-21T03:08:07.934+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T03:08:07.934+0000] {taskinstance.py:1284} INFO - Starting attempt 14 of 14
[2023-01-21T03:08:07.934+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T03:08:07.946+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2023-01-21 01:12:16.362883+00:00
[2023-01-21T03:08:07.950+0000] {standard_task_runner.py:55} INFO - Started process 840 to run task
[2023-01-21T03:08:07.953+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'example_spark_operator', 'python_job', 'manual__2023-01-21T01:12:16.362883+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/spark_dag.py', '--cfg-path', '/tmp/tmp1rtugxdq']
[2023-01-21T03:08:07.953+0000] {standard_task_runner.py:83} INFO - Job 273: Subtask python_job
[2023-01-21T03:08:08.026+0000] {task_command.py:389} INFO - Running <TaskInstance: example_spark_operator.python_job manual__2023-01-21T01:12:16.362883+00:00 [running]> on host 3cc77177a430
[2023-01-21T03:08:08.083+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=example_spark_operator
AIRFLOW_CTX_TASK_ID=python_job
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T01:12:16.362883+00:00
AIRFLOW_CTX_TRY_NUMBER=14
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-21T01:12:16.362883+00:00
[2023-01-21T03:08:08.090+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-01-21T03:08:08.091+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master spark://tomi-H310:7077 --name arrow-spark --queue root.default /home/tomi/streamingPipelineMercadoLibre/docker_***/dags/pi.py
[2023-01-21T03:08:08.188+0000] {spark_submit.py:495} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-01-21T03:08:09.749+0000] {spark_submit.py:495} INFO - python3: can't open file '/home/tomi/streamingPipelineMercadoLibre/docker_***/dags/pi.py': [Errno 2] No such file or directory
[2023-01-21T03:08:09.758+0000] {spark_submit.py:495} INFO - 23/01/21 03:08:09 INFO ShutdownHookManager: Shutdown hook called
[2023-01-21T03:08:09.760+0000] {spark_submit.py:495} INFO - 23/01/21 03:08:09 INFO ShutdownHookManager: Deleting directory /tmp/spark-73ca1b1f-9eee-4c1b-ab83-193fc1c01197
[2023-01-21T03:08:09.834+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 427, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://tomi-H310:7077 --name arrow-spark --queue root.default /home/tomi/streamingPipelineMercadoLibre/docker_***/dags/pi.py. Error code is: 2.
[2023-01-21T03:08:09.839+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=example_spark_operator, task_id=python_job, execution_date=20230121T011216, start_date=20230121T030807, end_date=20230121T030809
[2023-01-21T03:08:09.856+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 273 for task python_job (Cannot execute: spark-submit --master spark://tomi-H310:7077 --name arrow-spark --queue root.default /home/tomi/streamingPipelineMercadoLibre/docker_***/dags/pi.py. Error code is: 2.; 840)
[2023-01-21T03:08:09.892+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T03:08:09.922+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
