[2023-01-21T03:05:24.324+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_spark_operator.python_job manual__2023-01-21T01:12:16.362883+00:00 [queued]>
[2023-01-21T03:05:24.333+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_spark_operator.python_job manual__2023-01-21T01:12:16.362883+00:00 [queued]>
[2023-01-21T03:05:24.333+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T03:05:24.333+0000] {taskinstance.py:1284} INFO - Starting attempt 12 of 12
[2023-01-21T03:05:24.333+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T03:05:24.345+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2023-01-21 01:12:16.362883+00:00
[2023-01-21T03:05:24.349+0000] {standard_task_runner.py:55} INFO - Started process 554 to run task
[2023-01-21T03:05:24.351+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'example_spark_operator', 'python_job', 'manual__2023-01-21T01:12:16.362883+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/spark_dag.py', '--cfg-path', '/tmp/tmp1c55oow3']
[2023-01-21T03:05:24.352+0000] {standard_task_runner.py:83} INFO - Job 271: Subtask python_job
[2023-01-21T03:05:24.406+0000] {task_command.py:389} INFO - Running <TaskInstance: example_spark_operator.python_job manual__2023-01-21T01:12:16.362883+00:00 [running]> on host 3cc77177a430
[2023-01-21T03:05:24.465+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=example_spark_operator
AIRFLOW_CTX_TASK_ID=python_job
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T01:12:16.362883+00:00
AIRFLOW_CTX_TRY_NUMBER=12
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-21T01:12:16.362883+00:00
[2023-01-21T03:05:24.472+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-01-21T03:05:24.473+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master spark://tomi-H310:7077 --name arrow-spark --queue root.default /opt/spark/spark-3.3.1-bin-hadoop3/examples/src/main/python/pi.py
[2023-01-21T03:05:24.583+0000] {spark_submit.py:495} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-01-21T03:05:26.884+0000] {spark_submit.py:495} INFO - python3: can't open file '/opt/spark/spark-3.3.1-bin-hadoop3/examples/src/main/python/pi.py': [Errno 2] No such file or directory
[2023-01-21T03:05:26.904+0000] {spark_submit.py:495} INFO - 23/01/21 03:05:26 INFO ShutdownHookManager: Shutdown hook called
[2023-01-21T03:05:26.907+0000] {spark_submit.py:495} INFO - 23/01/21 03:05:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-80f6c3c0-4cce-40bc-acb9-e5d4cfba6702
[2023-01-21T03:05:26.948+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 427, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://tomi-H310:7077 --name arrow-spark --queue root.default /opt/spark/spark-3.3.1-bin-hadoop3/examples/src/main/python/pi.py. Error code is: 2.
[2023-01-21T03:05:26.952+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=example_spark_operator, task_id=python_job, execution_date=20230121T011216, start_date=20230121T030524, end_date=20230121T030526
[2023-01-21T03:05:26.964+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 271 for task python_job (Cannot execute: spark-submit --master spark://tomi-H310:7077 --name arrow-spark --queue root.default /opt/spark/spark-3.3.1-bin-hadoop3/examples/src/main/python/pi.py. Error code is: 2.; 554)
[2023-01-21T03:05:26.980+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T03:05:26.996+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
