[2023-02-09T21:57:18.935+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Status_info_postgres manual__2023-02-09T21:55:30.145767+00:00 [queued]>
[2023-02-09T21:57:18.944+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Status_info_postgres manual__2023-02-09T21:55:30.145767+00:00 [queued]>
[2023-02-09T21:57:18.944+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T21:57:18.944+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-02-09T21:57:18.944+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T21:57:18.959+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Status_info_postgres> on 2023-02-09 21:55:30.145767+00:00
[2023-02-09T21:57:18.967+0000] {standard_task_runner.py:55} INFO - Started process 1101 to run task
[2023-02-09T21:57:18.970+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Streaming_pipeline_meli', 'Status_info_postgres', 'manual__2023-02-09T21:55:30.145767+00:00', '--job-id', '1507', '--raw', '--subdir', 'DAGS_FOLDER/streamPipeline.py', '--cfg-path', '/tmp/tmpzvm_u7rx']
[2023-02-09T21:57:18.971+0000] {standard_task_runner.py:83} INFO - Job 1507: Subtask Status_info_postgres
[2023-02-09T21:57:19.025+0000] {task_command.py:389} INFO - Running <TaskInstance: Streaming_pipeline_meli.Status_info_postgres manual__2023-02-09T21:55:30.145767+00:00 [running]> on host b0a2a9b8da88
[2023-02-09T21:57:19.087+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Streaming_pipeline_meli
AIRFLOW_CTX_TASK_ID=Status_info_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T21:55:30.145767+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-09T21:55:30.145767+00:00
[2023-02-09T21:57:19.088+0000] {postgresStatus.py:28} ERROR - Ocurrio un error al conectarse a la base de datos de aws rds: invalid integer value "your port" for connection option "port"

[2023-02-09T21:57:19.088+0000] {python.py:177} INFO - Done. Returned value was: (False, OperationalError('invalid integer value "your port" for connection option "port"\n'))
[2023-02-09T21:57:19.095+0000] {xcom.py:635} ERROR - Object of type OperationalError is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-02-09T21:57:19.098+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type OperationalError is not JSON serializable
[2023-02-09T21:57:19.105+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Streaming_pipeline_meli, task_id=Status_info_postgres, execution_date=20230209T215530, start_date=20230209T215718, end_date=20230209T215719
[2023-02-09T21:57:19.119+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1507 for task Status_info_postgres (Object of type OperationalError is not JSON serializable; 1101)
[2023-02-09T21:57:19.141+0000] {local_task_job.py:159} INFO - Task exited with return code 1
