[2023-01-17T19:52:56.258+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [queued]>
[2023-01-17T19:52:56.268+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [queued]>
[2023-01-17T19:52:56.268+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T19:52:56.269+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-01-17T19:52:56.269+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T19:52:56.284+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): producer> on 2023-01-17 19:52:55.119227+00:00
[2023-01-17T19:52:56.288+0000] {standard_task_runner.py:55} INFO - Started process 3745 to run task
[2023-01-17T19:52:56.290+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'producer', 'manual__2023-01-17T19:52:55.119227+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmplwymhwnw']
[2023-01-17T19:52:56.291+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask producer
[2023-01-17T19:52:56.402+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [running]> on host ecc0273d1d42
[2023-01-17T19:52:56.543+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=producer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T19:52:55.119227+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T19:52:55.119227+00:00
[2023-01-17T19:52:56.544+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/producer_dag.py", line 27, in runKafkaProducer
    producer = KafkaProducer(bootstrap_servers=['localhost:9092'],
NameError: name 'KafkaProducer' is not defined
[2023-01-17T19:52:56.550+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Kafka_consumer, task_id=producer, execution_date=20230117T195255, start_date=20230117T195256, end_date=20230117T195256
[2023-01-17T19:52:56.561+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task producer (name 'KafkaProducer' is not defined; 3745)
[2023-01-17T19:52:56.583+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T19:52:56.599+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
