[2023-01-18T20:26:54.538+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [queued]>
[2023-01-18T20:26:54.547+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [queued]>
[2023-01-18T20:26:54.547+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T20:26:54.547+0000] {taskinstance.py:1284} INFO - Starting attempt 27 of 32
[2023-01-18T20:26:54.548+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T20:26:54.560+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): producer> on 2023-01-17 19:52:55.119227+00:00
[2023-01-18T20:26:54.565+0000] {standard_task_runner.py:55} INFO - Started process 1336 to run task
[2023-01-18T20:26:54.567+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'producer', 'manual__2023-01-17T19:52:55.119227+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmp4qj4fij0']
[2023-01-18T20:26:54.567+0000] {standard_task_runner.py:83} INFO - Job 40: Subtask producer
[2023-01-18T20:26:54.615+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [running]> on host 7a3ca62d008e
[2023-01-18T20:26:54.675+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=producer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T19:52:55.119227+00:00
AIRFLOW_CTX_TRY_NUMBER=27
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T19:52:55.119227+00:00
[2023-01-18T20:26:54.677+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]>: connecting to 0.0.0.0:9092 [('0.0.0.0', 9092) IPv4]
[2023-01-18T20:26:54.677+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-01-18T20:26:54.677+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]> returned error 111. Disconnecting.
[2023-01-18T20:26:54.677+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-18T20:26:54.727+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]>: connecting to 0.0.0.0:9092 [('0.0.0.0', 9092) IPv4]
[2023-01-18T20:26:54.727+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]> returned error 111. Disconnecting.
[2023-01-18T20:26:54.727+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-18T20:26:54.727+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/producer_dag.py", line 10, in runKafkaProducer
    value_serializer=lambda x: json.dumps(x).encode('utf-8'))
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-01-18T20:26:54.734+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Kafka_consumer, task_id=producer, execution_date=20230117T195255, start_date=20230118T202654, end_date=20230118T202654
[2023-01-18T20:26:54.743+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 40 for task producer (NoBrokersAvailable; 1336)
[2023-01-18T20:26:54.779+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T20:26:54.835+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
