[2023-01-18T16:57:29.623+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [queued]>
[2023-01-18T16:57:29.631+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [queued]>
[2023-01-18T16:57:29.631+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T16:57:29.632+0000] {taskinstance.py:1284} INFO - Starting attempt 11 of 16
[2023-01-18T16:57:29.632+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T16:57:29.644+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): producer> on 2023-01-17 19:52:55.119227+00:00
[2023-01-18T16:57:29.647+0000] {standard_task_runner.py:55} INFO - Started process 1909 to run task
[2023-01-18T16:57:29.649+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'producer', 'manual__2023-01-17T19:52:55.119227+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmprpicb5uy']
[2023-01-18T16:57:29.649+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask producer
[2023-01-18T16:57:29.694+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [running]> on host bd83d43de0a6
[2023-01-18T16:57:29.753+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=producer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T19:52:55.119227+00:00
AIRFLOW_CTX_TRY_NUMBER=11
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T19:52:55.119227+00:00
[2023-01-18T16:57:29.753+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/producer_dag.py", line 6, in runKafkaProducer
    producer = KafkaProducer(bootstrap_servers=['localhost:9092'],
NameError: name 'KafkaProducer' is not defined
[2023-01-18T16:57:29.760+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Kafka_consumer, task_id=producer, execution_date=20230117T195255, start_date=20230118T165729, end_date=20230118T165729
[2023-01-18T16:57:29.771+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 22 for task producer (name 'KafkaProducer' is not defined; 1909)
[2023-01-18T16:57:29.780+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T16:57:29.795+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
