[2023-01-18T21:25:45.561+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [queued]>
[2023-01-18T21:25:45.571+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [queued]>
[2023-01-18T21:25:45.571+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T21:25:45.571+0000] {taskinstance.py:1284} INFO - Starting attempt 46 of 50
[2023-01-18T21:25:45.571+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T21:25:45.585+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): producer> on 2023-01-17 19:52:55.119227+00:00
[2023-01-18T21:25:45.590+0000] {standard_task_runner.py:55} INFO - Started process 761 to run task
[2023-01-18T21:25:45.592+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'producer', 'manual__2023-01-17T19:52:55.119227+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmp968soh52']
[2023-01-18T21:25:45.593+0000] {standard_task_runner.py:83} INFO - Job 60: Subtask producer
[2023-01-18T21:25:45.646+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.producer manual__2023-01-17T19:52:55.119227+00:00 [running]> on host f2df97c6ee42
[2023-01-18T21:25:45.709+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=producer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T19:52:55.119227+00:00
AIRFLOW_CTX_TRY_NUMBER=46
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T19:52:55.119227+00:00
[2023-01-18T21:25:45.711+0000] {conn.py:1532} WARNING - DNS lookup failed for :9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2023-01-18T21:25:45.711+0000] {conn.py:316} ERROR - DNS lookup failed for :9092 (AddressFamily.AF_UNSPEC)
[2023-01-18T21:25:45.711+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-01-18T21:25:45.712+0000] {conn.py:1532} WARNING - DNS lookup failed for :9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2023-01-18T21:25:45.712+0000] {conn.py:316} ERROR - DNS lookup failed for :9092 (AddressFamily.AF_UNSPEC)
[2023-01-18T21:25:45.712+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/producer_dag.py", line 10, in runKafkaProducer
    value_serializer=lambda x: json.dumps(x).encode('utf-8'))
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-01-18T21:25:45.718+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Kafka_consumer, task_id=producer, execution_date=20230117T195255, start_date=20230118T212545, end_date=20230118T212545
[2023-01-18T21:25:45.728+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 60 for task producer (NoBrokersAvailable; 761)
[2023-01-18T21:25:45.764+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T21:25:45.778+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
