[2023-01-31T20:35:15.556+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Uploading_data_to_aws_rds manual__2023-01-31T16:01:06.868325+00:00 [queued]>
[2023-01-31T20:35:15.564+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Uploading_data_to_aws_rds manual__2023-01-31T16:01:06.868325+00:00 [queued]>
[2023-01-31T20:35:15.565+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T20:35:15.565+0000] {taskinstance.py:1284} INFO - Starting attempt 23 of 28
[2023-01-31T20:35:15.565+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T20:35:15.578+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Uploading_data_to_aws_rds> on 2023-01-31 16:01:06.868325+00:00
[2023-01-31T20:35:15.581+0000] {standard_task_runner.py:55} INFO - Started process 21641 to run task
[2023-01-31T20:35:15.584+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Streaming_pipeline_meli', 'Uploading_data_to_aws_rds', 'manual__2023-01-31T16:01:06.868325+00:00', '--job-id', '1336', '--raw', '--subdir', 'DAGS_FOLDER/streamPipeline.py', '--cfg-path', '/tmp/tmpliv9mpcx']
[2023-01-31T20:35:15.585+0000] {standard_task_runner.py:83} INFO - Job 1336: Subtask Uploading_data_to_aws_rds
[2023-01-31T20:35:15.633+0000] {task_command.py:389} INFO - Running <TaskInstance: Streaming_pipeline_meli.Uploading_data_to_aws_rds manual__2023-01-31T16:01:06.868325+00:00 [running]> on host 15c99fd3082a
[2023-01-31T20:35:15.691+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Streaming_pipeline_meli
AIRFLOW_CTX_TASK_ID=Uploading_data_to_aws_rds
AIRFLOW_CTX_EXECUTION_DATE=2023-01-31T16:01:06.868325+00:00
AIRFLOW_CTX_TRY_NUMBER=23
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-31T16:01:06.868325+00:00
[2023-01-31T20:35:15.692+0000] {loadDataToRds.py:8} INFO - Conexion exitosa a la base de datos de aws rds: None
[2023-01-31T20:35:15.692+0000] {loadDataToRds.py:19} ERROR - Ocurrio un error al subir los datos a aws rds: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?

[2023-01-31T20:35:15.692+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-31T20:35:15.699+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=Streaming_pipeline_meli, task_id=Uploading_data_to_aws_rds, execution_date=20230131T160106, start_date=20230131T203515, end_date=20230131T203515
[2023-01-31T20:35:15.715+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-31T20:35:15.731+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
