[2023-01-21T01:02:39.504+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.consumer_data_of_topic manual__2023-01-19T22:08:17.592063+00:00 [queued]>
[2023-01-21T01:02:39.513+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.consumer_data_of_topic manual__2023-01-19T22:08:17.592063+00:00 [queued]>
[2023-01-21T01:02:39.513+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T01:02:39.513+0000] {taskinstance.py:1284} INFO - Starting attempt 9 of 14
[2023-01-21T01:02:39.513+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T01:02:39.525+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): consumer_data_of_topic> on 2023-01-19 22:08:17.592063+00:00
[2023-01-21T01:02:39.529+0000] {standard_task_runner.py:55} INFO - Started process 2938 to run task
[2023-01-21T01:02:39.531+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'consumer_data_of_topic', 'manual__2023-01-19T22:08:17.592063+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmp57nwkgle']
[2023-01-21T01:02:39.532+0000] {standard_task_runner.py:83} INFO - Job 247: Subtask consumer_data_of_topic
[2023-01-21T01:02:39.595+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.consumer_data_of_topic manual__2023-01-19T22:08:17.592063+00:00 [running]> on host 3c73d3ee891b
[2023-01-21T01:02:39.652+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=consumer_data_of_topic
AIRFLOW_CTX_EXECUTION_DATE=2023-01-19T22:08:17.592063+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-19T22:08:17.592063+00:00
[2023-01-21T01:02:39.659+0000] {spark_submit.py:223} INFO - Could not load connection string spark_default, defaulting to yarn
[2023-01-21T01:02:39.660+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /opt/spark/spark-3.3.1-bin-hadoop3/examples/src/main/python/pi.py
[2023-01-21T01:02:39.806+0000] {spark_submit.py:495} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-01-21T01:02:39.808+0000] {spark_submit.py:495} INFO - JAVA_HOME is not set
[2023-01-21T01:02:39.818+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 427, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /opt/spark/spark-3.3.1-bin-hadoop3/examples/src/main/python/pi.py. Error code is: 1.
[2023-01-21T01:02:39.821+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Kafka_consumer, task_id=consumer_data_of_topic, execution_date=20230119T220817, start_date=20230121T010239, end_date=20230121T010239
[2023-01-21T01:02:39.838+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 247 for task consumer_data_of_topic (Cannot execute: spark-submit --master yarn --name arrow-spark /opt/spark/spark-3.3.1-bin-hadoop3/examples/src/main/python/pi.py. Error code is: 1.; 2938)
[2023-01-21T01:02:39.863+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T01:02:39.879+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
