[2023-01-18T21:57:33.322+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [queued]>
[2023-01-18T21:57:33.330+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [queued]>
[2023-01-18T21:57:33.330+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T21:57:33.330+0000] {taskinstance.py:1284} INFO - Starting attempt 11 of 16
[2023-01-18T21:57:33.330+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T21:57:33.341+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): producer> on 2023-01-18 21:35:11.718856+00:00
[2023-01-18T21:57:33.346+0000] {standard_task_runner.py:55} INFO - Started process 2722 to run task
[2023-01-18T21:57:33.348+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'producer', 'manual__2023-01-18T21:35:11.718856+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmp4zlmfp9s']
[2023-01-18T21:57:33.349+0000] {standard_task_runner.py:83} INFO - Job 79: Subtask producer
[2023-01-18T21:57:33.396+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [running]> on host f2df97c6ee42
[2023-01-18T21:57:33.479+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=producer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T21:35:11.718856+00:00
AIRFLOW_CTX_TRY_NUMBER=11
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T21:35:11.718856+00:00
[2023-01-18T21:57:33.481+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]>: connecting to 0.0.0.0:9092 [('0.0.0.0', 9092) IPv4]
[2023-01-18T21:57:33.481+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-01-18T21:57:33.481+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]> returned error 111. Disconnecting.
[2023-01-18T21:57:33.482+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-18T21:57:33.531+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]>: connecting to 0.0.0.0:9092 [('0.0.0.0', 9092) IPv4]
[2023-01-18T21:57:33.531+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]> returned error 111. Disconnecting.
[2023-01-18T21:57:33.531+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=0.0.0.0:9092 <connecting> [IPv4 ('0.0.0.0', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-18T21:57:33.532+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/producer_dag.py", line 55, in runKafkaProducer
    value_serializer=lambda x: json.dumps(x).encode('utf-8'))
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-01-18T21:57:33.538+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Kafka_consumer, task_id=producer, execution_date=20230118T213511, start_date=20230118T215733, end_date=20230118T215733
[2023-01-18T21:57:33.547+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 79 for task producer (NoBrokersAvailable; 2722)
[2023-01-18T21:57:33.560+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T21:57:33.574+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
